### ISSUE TITLE
Cannot subscripe to Launchpad Service

### ISSUE THREAD

**Issue by kostadin-t** [SAP-samples/sme-partner-reference-application#11]
I tried many ways to find the Launchpad Service and it doesn't show up anywhere. I am using BTP Free trial account.
![image](https://user-images.githubusercontent.com/38324512/212930362-ce03ab31-4adc-4ea2-9301-b6a354e156d5.png)

**Comment by knutheusermann** [comment]
I adopted the service naming from "SAP Launchpad Service" to "SAP Build Work Zone" (branch "s4hc-int"). 
I fully understand your ask to build and deploy the sample application on a BTP trial account. However, we are currently focusing on the integration with S/4HANA Cloud and assume a productively usable customer or partner BTP account.
