### ISSUE TITLE
Issues with Hana Cloud Free instance

### ISSUE THREAD

**Issue by MichaelFlucher** [SAP-samples/sme-partner-reference-application#12]
Hi,

I'm trying to get `author-readings-mt` running in our Global Account using `hana-free` instance.
After deploying, the two servers `author-readings-srv` and `author-readings-mtx-srv` crash.
The error log shows, that the cause is given by `@sap/cds-mtx` with the following error:
```
ERR [ERROR] 0 items found when querying service_offerings with {"fieldQuery":"catalog_name eq 'hana'"}
```
Is there any configuration available, to get this working with `hana-free`?

**Comment by knutheusermann** [comment]
Hi Michael,
as of today the MTX-module does not support the service plan "hana-free". Please assign the HANA Cloud service using the service plan "hana".
Thanks a lot for pointing me to this gap in our tutorials, I will close this gap in the next version.
