### ISSUE TITLE
CSRF Tokens for Destinations

### ISSUE THREAD

**Issue by ilyabelozerovsap** [SAP-samples/sme-partner-reference-application#13]
We had tested the first version of the Partner Reference App. Some day it stopped working (enterprise project couldn't be created in S4HC). And the reason was - the CSRF token is not processed automatically by destinations. So you have to specify it additionally in package.json:

**Comment by ilyabelozerovsap** [comment]
"S4HC_API_ENTERPRISE_PROJECT_SRV_0002": {
        "kind": "odata-v2",
        "model": "srv/external/S4HC_API_ENTERPRISE_PROJECT_SRV_0002",
        "csrf": true,
        "csrfInBatch": true,

**Comment by ilyabelozerovsap** [comment]
I hope it will be helpful for the 2nd version as well.

**Comment by murthyvsap** [comment]
Hi Colleagues,

the CSRF token configuration is taken care in version 2 of the Partner Reference application.

for detailed configuration please refer to package.json (https://github.com/SAP-samples/partner-reference-application/blob/main-multi-tenant-features/package.json)

Please let us know if you need any further details from our end.

Regards
Murthy
