### ISSUE TITLE
missing explanation how to start the app

### ISSUE THREAD

**Issue by bvarwig** [SAP-samples/sme-partner-reference-application#4]
on https://github.com/SAP-samples/sme-partner-reference-application/blob/main/Tutorials/02-Develop-Core-Application.md you just write 
![image](https://user-images.githubusercontent.com/8438658/180444279-7ebb9389-08a8-4110-843b-a08c7d66ca71.png)

A new-bee would not know how to do this. Please add the missing MTA build and deploy steps via Business application Studio.  Or why did you advice to install the Studio? I assume you could have done everything with a local dev setup.

**Comment by knutheusermann** [comment]
Detailed description for local testing added.
